### ISSUE TITLE
crash _dispatchMonitorMessage

### ISSUE THREAD

**Issue by alexmalek** [smockle/homebridge-lutron-caseta#3]
Hey, seeing a crash in lutron-caseta-platform.js:90
accessory._dispatchMonitorMessage(commandFields);

Seems to happen on any home bridge interaction. I've triple checked the settings - any suggestions?

**Comment by smockle** [comment]
Hi @alexmalek, thanks for trying out the plugin. A couple questions to start:

* Which version of Node.js are you using? (`node --version`)
* Which version of the plugin do you have installed? (`npm ls -g --depth=0 | grep homebridge-lutron-caseta-smockle`)

There a few ways you can debug further:

1. Edit `bridgeConnection` section of the plugin `config.json` to include `"debug": true`, like this:
```JSON
"bridgeConnection": {
  "host": "192.168.1.2",
  "debug": true
},
```
then restart Homebridge. This will increase the number of log messages, which may help you identify the issue.

2. If that doesn’t show enough information, the steps in the “Debugging” section of the README will increase the number of log messages further: https://github.com/smockle/homebridge-lutron-caseta#debugging

3. Or, you could bypass Homebridge’s logging altogether and get data directly from the Smart Bridge Pro using `telnet -l lutron 192.168.1.2:23` (replacing `192.168.1.2` with your port).

4. Or if you don’t see anything in the logs, you might try deleting the `accessories` and `persist` directories in your Homebridge config directory. Depending on how you set up Homebridge, this may remove other accessories you added to HomeKit via Homebridge and associated automations. It’d be a technique of last resort.

If you’d like to share your `config.json` or logs, I’d be happy to take a look. Feel free to omit any private data, but please note the omissions.

**Comment by alexmalek** [comment]
Thanks for the quick response - trying this now. Will come back with results.

**Comment by alexmalek** [comment]
Feb 15 05:42:55 raspberrypi homebridge[2145]: Bridge connection processing line login:
Feb 15 05:42:55 raspberrypi homebridge[2145]: Bridge connection processing line password:
Feb 15 05:42:55 raspberrypi homebridge[2145]: Bridge connection processing line GNET>
Feb 15 05:43:22 raspberrypi homebridge[2145]: Bridge connection processing line ~DEVICE,5,2,3
Feb 15 05:43:23 raspberrypi homebridge[2145]: Bridge connection processing line ~DEVICE,5,2,4
Feb 15 05:43:23 raspberrypi homebridge[2145]: Bridge connection processing line ~OUTPUT,2,1,0.00
Feb 15 05:43:23 raspberrypi homebridge[2145]: /opt/node/lib/node_modules/homebridge-lutron-caseta-smockle/src/lutron-caseta-platform.js:90
Feb 15 05:43:23 raspberrypi homebridge[2145]:     accessory._dispatchMonitorMessage(commandFields);
Feb 15 05:43:23 raspberrypi homebridge[2145]:               ^
Feb 15 05:43:23 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=1/FAILURE
Feb 15 05:43:23 raspberrypi systemd[1]: homebridge.service: Unit entered failed state.
Feb 15 05:43:23 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.``

**Comment by alexmalek** [comment]
here is the debug output I get. What's interesting is that the pico works - it just doesn't run the right rule. I pressed the top button, which I assume is 1. But program 3 seems to have run, and then home bridge crashes.

**Comment by alexmalek** [comment]
Here is my config.json. trying to get one of those pico controllers with 5 buttons to work. 

        {
            "platform": "LutronCasetaPlatform",
            "bridgeConnection": {
                "host": "10.0.1.8",
                "debug": true
            },
            "accessories": [{
                "name": "FiveButtonRemote1",
                "type": "PJ2-3BRL",
                "integrationID": 5
            }]
        }

**Comment by e8link** [comment]
Also receiving the same errors as previously reported.

node -v
v11.10.0

npm ls -g --depth=0 | grep homebridge-lutron-caseta-smockle
├── homebridge-lutron-caseta-smockle@2.0.10


/usr/local/lib/node_modules/homebridge-lutron-caseta-smockle/src/lutron-caseta-platform.js:90
    accessory._dispatchMonitorMessage(commandFields);
              ^
TypeError: Cannot read property '_dispatchMonitorMessage' of undefined
    at LutronCasetaPlatform._dispatchMonitorMessage (/usr/local/lib/node_modules/homebridge-lutron-caseta-smockle/src/lutron-caseta-platform.js:90:15)
    at CasetaBridgeConnection.LutronCasetaPlatform.bridgeConnection.on (/usr/local/lib/node_modules/homebridge-lutron-caseta-smockle/src/lutron-caseta-platform.js:26:14)
    at CasetaBridgeConnection.emit (events.js:197:13)
    at CasetaBridgeConnection.receiveData (/usr/local/lib/node_modules/homebridge-lutron-caseta-smockle/src/caseta-bridge-connection.js:65:18)
    at Socket.CasetaBridgeConnection.socket.on.data (/usr/local/lib/node_modules/homebridge-lutron-caseta-smockle/src/caseta-bridge-connection.js:35:12)
    at Socket.emit (events.js:197:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:145:17)


Config.json:

{
	"bridge": {
		"name": "Homebridge2",
		"username": "CC:22:3D:E3:CE:52",
		"port": 59826,
		"pin": "031-45-169"
	},
	"accessories": [],
	"platforms": [{
			"platform": "RingAlarm",
			"email": "XXXXX",
			"password": "XXXX"
		},
		{
			"platform": "config",
			"name": "Config",
			"port": 8080,
			"sudo": false
		},
		{
			"platform": "ring-video-doorbell",
			"name": "Doorbell",
			"username": "XXXX",
			"password": "XXXXX",

			"options": {
				"retries": 5,
				"ttl": 5,
				"verboseP": false
			},
			"ringing": {
				"event": "single",
				"motion": false,
				"contact": false
			}
		},
		{
			"platform": "LutronCasetaPlatform",
			"bridgeConnection": {
				"host": "172.16.16.26"
			},
			"accessories": [{
				"name": "Kitchen Pico Side Entry ",
				"type": "PJ2-3BRL",
				"integrationID": 2
			}, {
				"name": "Kitchen Pico Den",
				"type": "PJ2-3BRL",
				"integrationID": 5
			}]
		}
	]
}

**Comment by smockle** [comment]
I’d struggled to reproduce this locally, but I finally found a reliable repro: I get this error when I interact with a non-Pico-Remote-device connected to my Lutron Caséta Smart Bridge Pro.

**Comment by smockle** [comment]
Thanks again for reporting this. As of `homebridge-lutron-caseta-smockle` version 2.0.12, this error has been fixed.

**Comment by alexmalek** [comment]
awesome sauce - will try this again today.
