### ISSUE TITLE
Configuration posted in readme is incorrect

### ISSUE THREAD

**Issue by e8link** [smockle/homebridge-lutron-caseta#4]
The configuration posted in the readme isn't correct.  I tried this configuration in a separate homebridge instance and homebridge fails to start.

**Comment by smockle** [comment]
@e8link Thanks for trying the plugin. I’m sorry it’s failing to start for you. I’d like to debug this, but I need more information to proceed:

* Which version of Node.js are you using? (`node --version`)
* Which version of the plugin do you have installed? (`npm ls -g --depth=0 | grep homebridge-lutron-caseta-smockle`)
* Did you complete each step in [Setup](https://github.com/smockle/homebridge-lutron-caseta#setup) without errors?
* Did you edit the [Configuration](https://github.com/smockle/homebridge-lutron-caseta#configuration) (replacing the values of `"type"` and `"integrationID"`, for example)?
* Could you please paste the errors you’re seeing when you try to start Homebridge?

**Comment by e8link** [comment]
There is an extra comma in the readme for this one:

{
      "name": "TwoButtonRemote1",
      "type": "PJ2-2B",
      "integrationID": 3,
    }, 

It should be:

{
      "name": "TwoButtonRemote1",
      "type": "PJ2-2B",
      "integrationID": 3
    }, 

I was able to get this work using node 10!!

I'm at version:
eric@ubuntu:~/.homebridge$ node -v
v10.15.3

If I upgrade to node 11, I start getting the dispatch monitor messages in the previous issue for some reason.   I'd go back and do some more testing on the node 11 version but it was a VM that I deleted.

**Comment by smockle** [comment]
> There is an extra comma in the readme for this one:

@e8link Thanks for pointing out the extraneous comma; I removed it in commit https://github.com/smockle/homebridge-lutron-caseta/commit/a5f4c6d9ef69998481178f33fa6218bff5a69ba1.

> I was able to get this work using node 10!!

I’m happy it’s working for you! Thanks again for trying this plugin. 😊

> If I upgrade to node 11, I start getting the dispatch monitor messages in the previous issue for some reason. I'd go back and do some more testing on the node 11 version but it was a VM that I deleted.

I run this plugin with Node.js 10 (the [current LTS release](https://github.com/nodejs/Release#release-schedule)). I don’t plan to develop or maintain Node.js 11 support, but I’m open to outside contributions.
