### ISSUE TITLE
Error in Logs

### ISSUE THREAD

**Issue by JordanPatterson** [smockle/homebridge-lutron-caseta#6]
I am on the recommended node release and plugin version.

pi@raspberrypi:~ $ sudo journalctl -f -u homebridge-- Logs begin at Wed 2019-05-08 13:33:24 BST. --
May 08 13:33:32 raspberrypi homebridge[304]:                                                       
May 08 13:33:32 raspberrypi homebridge[304]:                                                       
May 08 13:33:32 raspberrypi homebridge[304]: Or enter this code with your HomeKit app on your iOS device to pair with Homebridge:
May 08 13:33:32 raspberrypi homebridge[304]:                        
May 08 13:33:32 raspberrypi homebridge[304]:     ┌────────────┐
May 08 13:33:32 raspberrypi homebridge[304]:     │ 033-44-254 │
May 08 13:33:32 raspberrypi homebridge[304]:     └────────────┘
May 08 13:33:32 raspberrypi homebridge[304]:                        
May 08 13:33:32 raspberrypi homebridge[304]: [5/8/2019, 1:33:32 PM] Homebridge is running on port 51826.
May 08 13:33:32 raspberrypi homebridge[304]: [5/8/2019, 1:33:32 PM] [LutronCasetaPlatform] CasetaBridgeConnection error: connect ENETUNREACH 192.168.1.4:23 - Local (0.0.0.0:0)

**Comment by JordanPatterson** [comment]
My Raspberry Pi had an incorrect static DNS server configured.

**Comment by smockle** [comment]
Thanks for the update @JordanPatterson. I’m glad you were able to resolve the issue.
